[project]
name = "fullstack-tempalte"
dynamic = ["version"]
description = "Default template for PDM package"
authors = []
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.version]
path = "app/__init__.py"

[tool.uv]
package = false

[tool.pdm]
distribution = false
